pipeline {
    agent any
    
    environment {
        GITHUB_TOKEN = credentials('github-token')  // Jenkins credentials로 GITHUB_TOKEN 관리
        TELEGRAM_BOT_TOKEN = credentials('telegram-bot-token')  // Jenkins credentials로 TELEGRAM_BOT_TOKEN 관리
        PR_NOTICE_TELEGRAM_ID = credentials('pr-notice-telegram-id')  // Jenkins credentials로 PR_NOTICE_TELEGRAM_ID 관리
    }

    stages {
        stage('Checkout') {
            steps {
                // 기존 checkout scm 대신 명시적으로 Git 리포지토리를 설정합니다.
                git branch: 'dev', url: 'https://github.com/lgr-2024/test-jenkins.git', credentialsId: 'github-token'
            }
        }
        
        stage('Install Node.js') {
            tools {
                nodejs 'nodejs-22.11.0'  // Node.js 환경 설정 (Global Tool Configuration에서 설정한 이름)
            }
        }
        
        stage('Build') {
            steps {
                sh 'npm install -g pnpm'
                sh 'pnpm install'
                sh 'pnpm run test'
            }
        }
        
        stage('Run JavaScript Script') {
            steps {
                script {
                    withEnv(['GITHUB_TOKEN', 'TELEGRAM_BOT_TOKEN']) {
                        sh 'node ./.github/workflows/auto-reviewer.cjs'
                    }
                }
            }
        }
    }
}
